version: '3.4'
services:
  db:
    image: 'mysql:8'
    container_name: dtm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password',
      ]
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d  
    ports:
      - '3306:3306'
  dtm:
    depends_on:
      - db
    image: 'yedf/dtm:latest'
    container_name: dtm-svc
    environment:
      IS_DOCKER: '1'
      STORE_DRIVER: mysql
      STORE_HOST: db
      STORE_USER: root
      STORE_PASSWORD: '123456'
      STORE_PORT: 3306
      STORE_DB: "dtm"
    ports:
      - '36789:36789'
      - '36790:36790'
  dtmdemo.webapi:
    depends_on:
      - dtm
      - db
    image: ${DOCKER_REGISTRY-}dtmdemowebapi
    environment:
      ASPNETCORE_ENVIRONMENT: docker
    container_name: dtm-webapi-demo
    build:
      context: .
      dockerfile: DtmDemo.WebApi/Dockerfile
    ports:
      - '31293:80'
      - '31294:443'
